# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thisStrain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'

  # Pods for thisStrain

  target 'thisStrainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'thisStrainUITests' do
    # Pods for testing
  end

end
